FROM python:3.6-alpine

RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && mkdir -p /data/python
RUN pip install --upgrade pip && pip install pyppeteer requests cloudant pyquery

WORKDIR /data/python

CMD ["python3"]
