FROM debian:stretch

ENV TIME_ZONE=Asia/Shanghai

RUN rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime \
    && echo "* soft nproc 65535" >> /etc/security/limits.conf \
    && echo "* hard nproc 65535" >> /etc/security/limits.conf \
    && echo "* soft nofile 65535" >> /etc/security/limits.conf \
    && echo "* hard nofile 65535" >> /etc/security/limits.conf \
    && echo "fs.file-max=65535" >> /etc/sysctl.conf \

CMD ["bash"]